package com.donquijote.persistence;
// Generated 29/07/2014 10:56:33 PM by Hibernate Tools 3.6.0



/**
 * Authorities generated by hbm2java
 */
public class Authorities  implements java.io.Serializable {


     private int idauthority;
     private Users users;
     private String authority;
     private boolean estadoborrado;

    public Authorities() {
    }

    public Authorities(int idauthority, Users users, String authority, boolean estadoborrado) {
       this.idauthority = idauthority;
       this.users = users;
       this.authority = authority;
       this.estadoborrado = estadoborrado;
    }
   
    public int getIdauthority() {
        return this.idauthority;
    }
    
    public void setIdauthority(int idauthority) {
        this.idauthority = idauthority;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }
    public boolean isEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }




}


