package com.donquijote.persistence;
// Generated 29/07/2014 10:56:33 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idcliente;
     private String nombre;
     private String apellido;
     private String cedulaRuc;
     private String ciudad;
     private String direccion;
     private String telefono;
     private boolean estadoborrado;
     private Set facturas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idcliente, String nombre, String apellido, String cedulaRuc, String ciudad, String direccion, String telefono, boolean estadoborrado) {
        this.idcliente = idcliente;
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedulaRuc = cedulaRuc;
        this.ciudad = ciudad;
        this.direccion = direccion;
        this.telefono = telefono;
        this.estadoborrado = estadoborrado;
    }
    public Cliente(int idcliente, String nombre, String apellido, String cedulaRuc, String ciudad, String direccion, String telefono, boolean estadoborrado, Set facturas) {
       this.idcliente = idcliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedulaRuc = cedulaRuc;
       this.ciudad = ciudad;
       this.direccion = direccion;
       this.telefono = telefono;
       this.estadoborrado = estadoborrado;
       this.facturas = facturas;
    }
   
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedulaRuc() {
        return this.cedulaRuc;
    }
    
    public void setCedulaRuc(String cedulaRuc) {
        this.cedulaRuc = cedulaRuc;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public boolean isEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


