package com.donquijote.persistence;
// Generated 16/08/2014 08:36:45 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int idfactura;
     private Usuario usuario;
     private Cliente cliente;
     private String numerofactura;
     private double iva;
     private Date fechacompra;
     private boolean estadoborrado;
     private Set detalleFacturas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int idfactura, Usuario usuario, Cliente cliente, String numerofactura, double iva, Date fechacompra, boolean estadoborrado) {
        this.idfactura = idfactura;
        this.usuario = usuario;
        this.cliente = cliente;
        this.numerofactura = numerofactura;
        this.iva = iva;
        this.fechacompra = fechacompra;
        this.estadoborrado = estadoborrado;
    }
    public Factura(int idfactura, Usuario usuario, Cliente cliente, String numerofactura, double iva, Date fechacompra, boolean estadoborrado, Set detalleFacturas) {
       this.idfactura = idfactura;
       this.usuario = usuario;
       this.cliente = cliente;
       this.numerofactura = numerofactura;
       this.iva = iva;
       this.fechacompra = fechacompra;
       this.estadoborrado = estadoborrado;
       this.detalleFacturas = detalleFacturas;
    }
   
    public int getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(int idfactura) {
        this.idfactura = idfactura;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getNumerofactura() {
        return this.numerofactura;
    }
    
    public void setNumerofactura(String numerofactura) {
        this.numerofactura = numerofactura;
    }
    public double getIva() {
        return this.iva;
    }
    
    public void setIva(double iva) {
        this.iva = iva;
    }
    public Date getFechacompra() {
        return this.fechacompra;
    }
    
    public void setFechacompra(Date fechacompra) {
        this.fechacompra = fechacompra;
    }
    public boolean isEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public Set getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


