package com.donquijote.persistence;
// Generated 16/08/2014 08:36:45 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Rol rol;
     private String username;
     private String password;
     private String nombre;
     private String apellido;
     private String cedula;
     private Date fechanacimiento;
     private double salario;
     private boolean sexo;
     private boolean estadoborrado;
     private boolean enabled;
     private Set facturas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, Rol rol, String username, String password, String nombre, String apellido, String cedula, Date fechanacimiento, double salario, boolean sexo, boolean estadoborrado, boolean enabled) {
        this.idusuario = idusuario;
        this.rol = rol;
        this.username = username;
        this.password = password;
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula = cedula;
        this.fechanacimiento = fechanacimiento;
        this.salario = salario;
        this.sexo = sexo;
        this.estadoborrado = estadoborrado;
        this.enabled = enabled;
    }
    public Usuario(int idusuario, Rol rol, String username, String password, String nombre, String apellido, String cedula, Date fechanacimiento, double salario, boolean sexo, boolean estadoborrado, boolean enabled, Set facturas) {
       this.idusuario = idusuario;
       this.rol = rol;
       this.username = username;
       this.password = password;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedula = cedula;
       this.fechanacimiento = fechanacimiento;
       this.salario = salario;
       this.sexo = sexo;
       this.estadoborrado = estadoborrado;
       this.enabled = enabled;
       this.facturas = facturas;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public boolean isSexo() {
        return this.sexo;
    }
    
    public void setSexo(boolean sexo) {
        this.sexo = sexo;
    }
    public boolean isEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


